[FIX] industry_fsm_sale_report: prevent error on installing module
Currently a 'ParseError' is arising when the user installs the
'industry_fsm_sale_report' module after deleting 'Field Service' product from
the products.

Steps to reproduce:
- Install the 'industry_fsm_sale' module
- Delete 'Field Service' from products
- Now install 'industry_fsm_sale_report' module

Traceback:
Exception: Cannot update missing record 'industry_fsm_sale.field_service_product'

ParseError: while parsing /home/odoo/src/enterprise/saas-18.1/industry_fsm_sale_report/data/product_product_data.xml:4, somewhere inside
<record id="industry_fsm_sale.field_service_product" model="product.product">
            <field name="worksheet_template_id" ref="industry_fsm_report.fsm_worksheet_template"/>
        </record>

This commit solves the above issue by using forcecreate="False" to bypass
record creation if it violates checks.

sentry-5731062091

closes odoo/enterprise#79744

X-original-commit: b1bbc4052812435ebc39d181e49e0545a8323d3b
Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>