[FIX] l10n_ro_reports: Explicitly remove groupby from records
Some of the records had their `groupby` set to `account_id` in previous versions
That field was removed from the data file and new expressions were added.
This means that the records which already have `groupby` set won't get that
field updated during an upgrade, and will trigger an error:
https://github.com/odoo/odoo/blob/17.0/addons/account/models/account_report.py#L571-L578

By explicitly removing the value from the field, we ensure the field will be
emptied.

```
odoo.tools.convert.ParseError: while parsing /home/odoo/src/enterprise/17.0/l10n_ro_reports/data/balance_sheet_short.xml:3
Groupby feature isn't supported by aggregation engine. Please remove the groupby value on 'SOLDE C | 43'
```

closes odoo/enterprise#63864

X-original-commit: bd27b96726cdc4b6ceeda3cb6136440a904783ad
Signed-off-by: Julien Van Roy (juvr) <juvr@odoo.com>
Signed-off-by: Agustín Castro Bugallo (agcb) <agcb@odoo.com>