[FIX] l10n_jp_zengin: fix code while append error message
An error occurs when the system try to raises an error message when a
bank accout have not client code.

TypeError: list.append() takes no keyword arguments

Currently in code [1] mistakenly provides multiple values via keyword arguments
to the append method. which is incorrect. So instead of it, we need to change
the formatting to pass a single argument as a string to resolve the error.

Link [1]: https://github.com/odoo/enterprise/blob/07fae63e381dfa7a8035f67837f19d619600d434/l10n_jp_zengin/models/account_batch_payment.py#L77

Sentry-6128197646

closes odoo/enterprise#75635

X-original-commit: 92db7f28a2fcb6377f10bcd42ebbdc4fc2869219
Signed-off-by: Meet Gandhi (mega) <mega@odoo.com>