[FIX] l10n_cl_edi_pos: error on cash operation
With a CL company setup
Open POS session
Click Cash In/Out
Select an amount
Confirm

Error: TypeError: Cannot read properties of undefined (reading 'l10n_cl_sii_regional_office')
It occurs because this specific call to `getReceiptHeaderData` is made
without order

opw-3917776

closes odoo/enterprise#62985

Signed-off-by: Vlad Stroia (vlst) <vlst@odoo.com>