[FIX] account_budget: constraint check on account_ids
Activate 'Budget Management'
In Accounting>Configuration>Management>Budgetary Positions
Create a new Budgetary Position
Add some accounts
Save
Remove an account
Save

ValidationError: The budget must have at least one account

This occurs because there was a change in the write commands sent
Up to saas-16.4 we used to receive a set command even when we just
delete m2m objects
`{'account_ids': [[Command.set, False, ids]]}`
We now have only unlink operations
`{'account_ids': [[Command.unlink, id]]}`
and the old way of checking the updated `account_ids` no longer works

opw-3633650

closes odoo/enterprise#54323

Signed-off-by: Olivier Colson (oco) <oco@odoo.com>