[FIX] product_barcodelookup: prevent error when creating a product with barcode
When the user creates a new product with barcode and tries to save it,
a traceback will appear.

Steps to reproduce the error:
- Install "product_barcodelookup" module
- Add the API key for barcode lookup in settings
- Create new product > add barcode(ex. 817882025607) > Save

Error: A traceback appears:
AttributeError: 'uom.uom' object has no attribute
'_get_weight_uom_id_from_ir_config_parameter'

https://github.com/odoo/enterprise/blob/058a2b63d3272d6b7fd52afba7951c56494b68f5/product_barcodelookup/models/product_template.py#L55
Here, "uom.uom" model has no _get_weight_uom_id_from_ir_config_parameter method.
so It will lead to the above traceback.

sentry-5373607708

closes odoo/enterprise#62852

X-original-commit: ee506c2ab3e7b39831aed0af2142f8f7e4ba02ba
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>
Signed-off-by: Renilkumar Kajavadra (reka) <reka@odoo.com>