[FIX] l10n_mx_edi_stock: incorrect method called during stock picking
This issue occurs when a customer creates a delivery order using the inventory
module, validates it, and then tries to generate the delivery guide for that
order. At that time error will be generated.

step to reproduce:
- Install the `l10n_mx_edi_stock` Module.
- switch the company of `ESCUELA KEMPER URGATE`
- open the `Inventory`
- create the delivery order  > validate it.
- click on `Generate Delivery Guide` button.
- the error will be generated,

error-AttributeError
'stock.picking' object has no attribute '_l10n_mx_edi_cfdi_invoice_document_sent_failed'

https://github.com/odoo/enterprise/blob/17.0/l10n_mx_edi_stock/models/stock_picking.py#L362

https://github.com/odoo/enterprise/blob/17.0/l10n_mx_edi_stock/models/stock_picking.py#L264

The reason for this error is that the method that called
`l10n_mx_edi_cfdi_invoice_document_sent_failed` instead of
`_l10n_mx_edi_cfdi_document_sent_failed` was called incorrectly.

sentry-4621933269

closes odoo/enterprise#50791

Signed-off-by: Laurent Smet (las) <las@odoo.com>