[FIX] account_reports: prevent an error when open a profit and loss report
Currently, An error is generated while a user is trying to open the
'Profit and Loss' report when  balance sheet report is not available

Steps to reproduce:

- Install an 'account_reports' module.
- Turn on debugger mode.
- Navigate to Accounting / Configuration / Management / Accounting Reports,
Delete the 'Balance Sheet' report
- And Open 'Profit and Loss' report(In Accounting Reports).

ValueError: External ID not found in the system: account_reports.balance_sheet

An error occurs when the system tries to retrieve an external id of balance
sheet report 'account_reports.balance_sheet' at [1], but it is not available.

Link [1]: https://github.com/odoo/enterprise/blob/9d185d78813f776249a4de0469d659723a94d026/account_reports/models/account_report.py#L5401

To handle this issue, add 'raise_if_not_found=False' in ref() so that when
balance sheet report is not available it will return a None value instead of
traceback.

Sentry-5836075163

closes odoo/enterprise#69989

Signed-off-by: Olivier Colson (oco) <oco@odoo.com>