[FIX] sale_subscription: is_subscription should trigger subscription_change update
compute_is_subscription is reading subscription_state values and
subscription_state depends on is_subscription.

As both fields are computed and depends on each other and
compute subscription_state does not update the subscription_state at
each call (the method act as a default value), we need this hack to
prevent this error in test_subscription_state
Please enter the commit message for your changes. Lines starting

```
2023-12-14 13:30:20,269 79001 ERROR no_data odoo.addons.sale_subscription.tests.test_sale_subscription: FAIL: TestSubscription.test_subscription_state
Traceback (most recent call last):
  File "/home/arj/PycharmProjects/worktree/saas-16.4/enterprise/sale_subscription/tests/test_sale_subscription.py", line 2113, in test_subscription_state
    self.assertEqual(sub_2.subscription_state, '1_draft')
AssertionError: False != '1_draft'

```

This is occuring because _compute_subscription_state is not retriggered
after `sub_2.recurrence_id = self.recurrence_month.id` in the test
without demo data.
_compute_is_subscription is True but the subscription_state is not
retriggered.

We could:
1) call the compute method in the test. We don't want that.
2) call self.assertEqual(sub_2.subscription_state, '1_draft') after
   `sub_2.recurrence_id = self.recurrence_month.id` and before the
   addition of the line. it's a bad idea because it hide the issue under
   the carpet and the compute remains broken.
3) add subscription_state to the fields to recompute to make sure the
   update is done.

Part-of: odoo/enterprise#52936