[FIX] account_accountant: statement line deadlock
The aim of this commit is to prevent the CRON
`account_account.auto_reconcile_bank_statement_line` to fail due a deadlock.

Solution:
Wait and acquire a lock to be on those lines with a `FOR UPDATE` clause.
This will prevent any other transaction from writing on those lines.
The lock will be released at commit/rollback.
We don't commit nor rollback in the method to prevent any undesired side
effect.
We either expect the caller to commit/rollback manually or to let the
ORM do it on its own like in a CRON for example.

Notes:
We spotted a lot of deadlock in or lock due to that CRON.
We saw that it could rollback the write on a lot of row at the same
time and could prevent the cron to call itself for the next execution.

Traceback: (VALUES where removed for readability, there were 100 of them)
```
2025-01-27 12:00:39,276 3822296 ERROR openerp odoo.sql_db: bad query: b'UPDATE "account_bank_statement_line"
SET "cron_last_check" = "__tmp"."cron_last_check"::timestamp, "write_date" = "__tmp"."write_date"::timestamp, "write_uid" = "__tmp"."write_uid"::int4
FROM (VALUES (...), (...), (...), (...), ) AS "__tmp"("id", "cron_last_check", "write_date", "write_uid")
WHERE "account_bank_statement_line"."id" = "__tmp"."id"'
ERROR: deadlock detected
DETAIL:  Process 934692 waits for ShareLock on transaction 2414965881; blocked by process 932819.
Process 932819 waits for ShareLock on transaction 2414966299; blocked by process 934692.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (10685,6) in relation "account_bank_statement_line"

2025-01-27 12:00:39,277 3822296 ERROR openerp odoo.addons.base.models.ir_cron: Job 'Try to reconcile automatically your statement lines' (297) server action #4952 failed
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_cron.py", line 572, in _callback
    self.env.flush_all()
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 833, in flush_all
    self[model_name].flush_model()
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 6707, in flush_model
    self._flush(fnames)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 6784, in _flush
    model.browse(some_ids)._write_multi(vals_list)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 4881, in _write_multi
    self.env.execute_query(SQL(
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 962, in execute_query
    self.cr.execute(query)
  File "/home/odoo/src/odoo/18.0/odoo/sql_db.py", line 373, in execute
    res = self._obj.execute(query, params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.DeadlockDetected: deadlock detected
DETAIL:  Process 934692 waits for ShareLock on transaction 2414965881; blocked by process 932819.
Process 932819 waits for ShareLock on transaction 2414966299; blocked by process 934692.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (10685,6) in relation "account_bank_statement_line"
```

closes odoo/enterprise#80284

Task-id: 4393854
X-original-commit: 5be831bd83f9696f697ca23e326d5f00ad116799
Signed-off-by: Florian Gilbert (flg) <flg@odoo.com>
Signed-off-by: Brice Bartoletti (bib) <bib@odoo.com>