[FIX] account_invoice_extract: prevent invisible key error
Steps to reproduce:
- Make studio view of account journal entry form view (account.journal.form).
- Find the node that exists on xpath "//field[@name='partner_id'][@widget='res_partner_many2one']"
and remove the invisible attribute from it.
- Upgrade database to saas-17.4
 
Traceback:
```
   File "/home/odoo/src/enterprise/saas-17.4/account_invoice_extract/models/account_invoice.py", line 900, in _get_view
    node.set('invisible', f"{placeholder_condition} or ({node.attrib.pop('invisible')})")
   File "src/lxml/etree.pyx,"  line 2464, in lxml.etree._Attrib.pop
KeyError: 'invisible'
```

Solution:
- This occurs because when checking the invisible attribute of a node, we are
not checking if an invisible attribute exists or not, so added
a condition for checking.

closes odoo/enterprise#70115

X-original-commit: 41068e29e8f916541e7fbe3d29e6a3fce021466a
Signed-off-by: Louis Baudoux (lba) <lba@odoo.com>
Signed-off-by: Karna Modasiya (kmod) <kmod@odoo.com>