[FIX] l10n_es_reports: fix boe export modelo 390
Exporting a BOE file for the modelo 390 generate a AttributeError ('account.report' object has no attribute 'export_boe'. Did you mean: 'export_file'?). This occurs because the 390 report use sections and it tries to run "export_boe" on the seciotn report instead of the handler report.

Steps to trigger the error:
    - display modelo 390 tax report with a spanish company
    - open the boe export wizard vie the "BOE" button
    - complete the wizard and click Generate BOE

This fix adds "l10n_es.mod390.tax.report.handler" as custom handlers to the sections enabling to call 'export_boe'

Task: 4453629
Part-of: odoo/enterprise#77941
Related: odoo/odoo#195380
Signed-off-by: Josse Colpaert (jco) <jco@odoo.com>