[FIX] website_sale_renting: correctly add files to bundle
Current behaviour:
When you click on the "request a document" link,
then upload a document, you get a CSRF error

Steps to reproduce:
1. Install documents
2. In documents, click the arrow next to "new", then "request"
3. Add a name, and a "request to", then click "request"
4. Go to messages, copy the link in the generated email
5. Paste the link in an incognito window
6. Upload a document, CSRF error

Cause of the issue:
The js file that adds the CSRF token (documents_public_pages.js)
could not be loaded due to an error caused by website_sale_renting:
TypeError: odoo.define is not a function

The mixin file was loaded before the odoo module loader.
Caused by: https://github.com/odoo/enterprise/commit/93d09071a08bd5de948886729d827b1c46e907d9

Fix:
Put js code from website_sale_renting before owl.js
which is right after assets_frontend_minimal,
containing module_loader.js

opw-4138333

closes odoo/enterprise#70577

Signed-off-by: Victor Feyens (vfe) <vfe@odoo.com>