[FIX] l10n_ar_reports: prevent syntax error while reading po file
Currently, a log error is occurring from [1] and [2] due to adding two msgids
instead of one there in the 'es_419.po' file. This is because the recently
refactored code https://github.com/odoo/enterprise/commit/c2a5c5950cf702c6ed77d8b94c7dfece3f127dc8
updated translations but added an extra msgid at [1] and [2].

Error: `OSError: Syntax error in po file (line 281)`

[1]-https://github.com/odoo/enterprise/blob/8e8e5b2f01c75f0131d8248997fa4059777e3fa1/l10n_ar_reports/i18n/es_419.po#L280-L281
[2]-https://github.com/odoo/enterprise/blob/8e8e5b2f01c75f0131d8248997fa4059777e3fa1/l10n_ar_reports/i18n/es_419.po#L459-L460

sentry-4963679418

closes odoo/enterprise#56566

X-original-commit: 71d2649c458178428512701d53437a0f32c69d2d
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>
Signed-off-by: ANSARI MAHAMADASIF (maan) <maan@odoo.com>