[FIX] account_reports: traceback on printing trial balance
before this commit, on printing trial balance report in
excel, raises an exception

when the level is None it cannot be compared with >= and
thus exception is shown

elif level >= 3:
TypeError: '>=' not supported between instances of
'NoneType' and 'int'

introduced in the commit: https://github.com/odoo/enterprise/commit/9d1f27082cc2e837951a3a5c3337cc90531de04a

after this commit, no error wont be shown when printing
trial balance in excel

closes odoo/enterprise#71871

X-original-commit: 6a1d653e6701ea2dc0d5e8ac0248df1c3d25657c
Signed-off-by: John Laterre (jol) <jol@odoo.com>