[FIX] spreadsheet_edition: Handling Empty spreadsheets Data
Issue:
------
When migrating a database having 'Documents' module installed and also
having empty/blank spreadsheets created in version saas-17.2 or lower will
lead to a JSON decoder error.This happens when the 'spreadsheet_data' value
become an empty `b''` because of empty spreadsheets.
Here :
https://github.com/odoo/enterprise/blob/17.0/spreadsheet_edition/models/spreadsheet_mixin.py#L224

Solution:
-----------
Passing an empty dictionay '{}' if it gets empty quotes as `b''` during processing.

Steps to reproduce:
------------------------
1. Create a database in version 17.2 or lower and install Documents module.
2. Create empty/blank spreadsheets (we can manually upload an empty spreadsheet).
3. Migrate the database to version saas~17.4 or above.
4. Finally, during testcases one of the test case will fail. Because of empty quotes.

Traceback:
```
   File "/home/odoo/src/enterprise/saas-17.4/spreadsheet_edition/models/spreadsheet_mixin.py", line 44, in _compute_current_revision_uuid
    snapshot = spreadsheet._get_spreadsheet_snapshot()
   File "/home/odoo/src/enterprise/saas-17.4/spreadsheet_edition/models/spreadsheet_mixin.py", line 234, in _get_spreadsheet_snapshot
    return json.loads(self.spreadsheet_data)
   File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
   File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

closes odoo/enterprise#74921

X-original-commit: 7502582bfefb35971a15ceef9d4b92ac145a9fe8
Signed-off-by: Lucas Lefèvre (lul) <lul@odoo.com>
Signed-off-by: Syed Nasir (syna) <syna@odoo.com>