[FIX] delivery_sendcloud: prevent error when validating delivery
When the customer clicks on the validate button in delivery with
Sendcloud carrier, a traceback will appear.

Steps to reproduce the error:
- Enable Sendcloud Connecter
- Go to Inventory > Configuration > Delivery Methods > Create new Method >
  Provider: SendCloud > Max Weight: 2 kg
- Create a new product A > Type: Goods > Weight: 10 kg
- Create a new Delivery > add Product A > Carrier: SendCloud > Validate

Traceback:
"AttributeError: 'SendCloud' object has no attribute 'env'"

https://github.com/odoo/enterprise/blob/5dd7022e079bbb45492356a66a60c98a249cec8a/delivery_sendcloud/models/sendcloud_service.py#L389
Here, "self" is used instead of "picking",
So, It will lead to the above traceback.

sentry-6086972478

closes odoo/enterprise#74699

X-original-commit: 5caa32b4e166c39e5d07f67de0280f5d35feadbb
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>
Signed-off-by: Renilkumar Kajavadra (reka) <reka@odoo.com>