[FIX] helpdesk: make helpdesk_fsm uninstall possible
Issue
-----
With helpdesk_fsm installed, uninstall helpdesk_fsm or any module
that will trigger its uninstallation (e.g. helpdesk):

Error:
```
in fields.py:
fields = records.pool.field_computed[self]
KeyError: 'helpdesk.team.fsm_project_id'
```

Cause
-----
Issue since 1da1467115726263e5cdc50354b4413f8bb7ca7d and the addition
of `use_fsm` as a dependency of `_compute_fsm_project_id`

When we uninstall any helpdesk module, we set to False the associated
fields of all helpdesk teams (mapped in `_get_field_modules`) for all
uninstalled modules.
https://github.com/odoo/enterprise/blob/9fba5f841c3c0710eb0cce00263bf914dac03dc6/helpdesk/models/ir_module.py#L13-L16

The change of `use_fsm` means `fsm_project_id` is marked as a field
to be recomputed. This happens at some point during a `flush_all`,
but after the field has been deleted in DB and a new registry has
been loaded without that field.

Change
-----
Force a recomputation by flushing the records.

opw-4338172
opw-4339801

closes odoo/enterprise#74473

X-original-commit: 373aa7829726973e5398bbbdcb6ef60a65687624
Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>
Signed-off-by: Tanguy Quéguineur (taqu) <taqu@odoo.com>