[FIX] whatsapp: fix webhook update for template quality UNKNOWN
When receiving a webhook to update for template quality it may crash
with the following error:

```
ValueError: Wrong value for whatsapp.template.quality: 'unknown'
```

As indicated in the reference documentation [^1], whatsapp use the
value `UNKOWN` whereas we're using `none` for `whatsapp.template`
quality, so this commit convert it to the appropriate value.

[^1]: https://developers.secure.facebook.com/docs/graph-api/reference/whats-app-business-account/message_templates/

closes odoo/enterprise#62915

X-original-commit: 69d2fe7ea1c3998c022f987a85f3e62918a5bb91
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>
Signed-off-by: Xavier Alt (xal) <xal@odoo.com>