[FIX] documents_account: avoid migrated document actions crashes
After this commit 574d608, The workflow actions have been removed and replaced
by server actions and this PR is responsible for handling the migration of
workflow actions into server actions.(see https://github.com/odoo/upgrade/pull/6729)

```
AttributeError: 'int' object has no attribute 'create_document_from_attachment'
```
We created server actions sending to `journal_id` as `int` when migrating
dbs to 18.0. While the method originally supported only recordsets,
it's actually convenient to support `int`s here to avoid browse in the action
(more readable and more accessible to end-users).

opw-4453249

closes odoo/enterprise#76599

Signed-off-by: Florian Charlier (flch) <flch@odoo.com>