[FIX] account_sepa_direct_debit: branch cannot validate SEPA batch payment
Create a branch company and switch to it
Activate SEPA Direct Debit (SDD) and add Creditor Identifier
Activate Batch Payments
Add a SEPA bank account on the Bank journal
Add a SEPA bank account on a partner
Create SEPA mandate for the partner bank account on the Bank journal
Make an invoice to the partner
Register payment with payment method "SEPA Direct Debit"
Go to Accounting>Customer>Payments
Select the payment > Hit 'Create Batch'
Validate creted batch

Issue: A traceback will raise
```py
  File "[...]/enterprise/account_sepa_direct_debit/models/account_payment.py", line 117, in _sdd_xml_gen_header
    create_xml_node_chain(InitgPty, ['Id','OrgId','Othr','Id'], company_id.sdd_creditor_identifier)
  File "[...]/odoo/tools/xml_utils.py", line 109, in create_xml_node_chain
    current_node.text = last_node_value
  File "src/lxml/etree.pyx", line 1039, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 747, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 735, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1538, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got 'bool'
```

This occurs because we assigned the credit identifier to the branch
company, but, when validating the batch, the system exports the
sdd xml from the company found on the journal, so the parent company
that have no Creditor Identifier defined

Issue2: After adding the Creditor Identifier on the parent company and trying
again, a validation an error will block the action

"Trying to generate a Direct Debit XML file containing payments from
another company than that file's creditor."

So we need also to allow exporting the xml file from child companies

opw-3943103

closes odoo/enterprise#65786

X-original-commit: 4a4bf537144069874033736823ceea3ce02e83b7
Signed-off-by: Olivier Colson (oco) <oco@odoo.com>
Signed-off-by: Andrea Grazioso (agr) <agr@odoo.com>