[FIX] web_studio: show the notification when creating unavailable view
This commit fix a bad usage of the notification service which leads to
a crash.

Steps to reproduce:

- Go to calendar
- Click on studio in the systray
- Click on views
- Click on the activity view to create one

Current Behaviour
-----------------

Crash: `Caused by: TypeError: this.child.mount is not a function`

Expected Behaviour
------------------
Display a notification indicating that the view cannot be created on
this model.

opw-3686237

closes odoo/enterprise#54624

X-original-commit: 8e089997f65afd7f206b7df6ce41a562baadd16e
Signed-off-by: Lucas Perais (lpe) <lpe@odoo.com>
Signed-off-by: Florent Dardenne (dafl) <dafl@odoo.com>