[FIX] l10n_ar_edi: remove `PKCS7_sign` usage
Steps to reproduce
-----------------
* use python 3.12
* install python requirements (requirements.txt)
* install `l10n_ar_edi`
* switch to an Argentinean company
* in the Invoicing settings, under the AFIP Web Services section, click
  'Test Connections'

You should be met with the following error: `AttributeError: module
'lib' has no attribute 'PKCS7_sign'`

Cause
-----
`PKCS7_sign()` was removed in recent versions of `pyopenssl`.

opw-4085411
opw-4085389

closes odoo/enterprise#68221

X-original-commit: c4d72ed4f952cf550e82444f0df77e8b87ae6782
Signed-off-by: John Laterre (jol) <jol@odoo.com>
Signed-off-by: Séna Serge Nshimiyimana (sesn) <sesn@odoo.com>