[FIX] sale_subscription: disable message_user_assigned when consolidated
Before this commit, when the invoice consolidation option was activated
and several user_id were set on subscription invoicing at the same time,
a traceback was observed:

```py
  File "/home/arj/PycharmProjects/worktree/17.0/odoo/addons/mail/models/mail_thread.py", line 276, in create
    thread._message_auto_subscribe(create_values, followers_existing_policy='update')
  File "/home/arj/PycharmProjects/worktree/17.0/odoo/addons/mail/models/mail_thread.py", line 4138, in _message_auto_subscribe
    res = self._message_auto_subscribe_followers(updated_values, def_ids)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arj/PycharmProjects/worktree/17.0/enterprise/sale_subscription/models/account_move.py", line 76, in _message_auto_subscribe_followers
    if salesperson and user_id == salesperson.id and user_id != self.env.user.id:
                                  ^^^^^^^^^^^^^^
  File "/home/arj/PycharmProjects/worktree/17.0/odoo/odoo/fields.py", line 5154, in __get__
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: res.users(56, 60)
```

closes odoo/enterprise#71188

Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>