[FIX] account_reports: traceback in general ledger export
Create a new journal entry
Post it
Reset to draft
Delete the name
Go to General Ledger
Export PDF

Error
TypeError: object of type 'NoneType' has no len()

This occurs because when the name field is blanked, it is set to None

opw-3925088

closes odoo/enterprise#63586

X-original-commit: 14834956dd2f9b2df2f4ac60e79d115a5e4e85e3
Signed-off-by: Habib Ayob (ayh) <ayh@odoo.com>