[FIX] l10n_mx_reports: traceback on posting close entry
With an MX company setup
Accounting > Reporting > Tax Report
Choose "Generic Tax Report", select last fiscal year period
Generate Closing Entry (Tax accounts needs to be configured)
Post the closing entry

Traceback will raise
AttributeError: 'account.report' object has no attribute 'action_periodic_vat_entries'

It is caused by a wrong inheritance of the MX tax report

opw-3846942

closes odoo/enterprise#61317

X-original-commit: 11cefcc9642b32d145cf0011781f4f175f2f9bd3
Signed-off-by: John Laterre (jol) <jol@odoo.com>
Signed-off-by: Andrea Grazioso (agr) <agr@odoo.com>