[FIX] l10n_es_reports: fix boe export modelo 390
Exporting a BOE file for the modelo 390 generate a AttributeError ('account.report' object has no attribute 'export_boe'. Did you mean: 'export_file'?). This occurs because the 390 report use sections and it tries to run "export_boe" on the seciotn report instead of the handler report.

Steps to trigger the error:
    - display modelo 390 tax report with a spanish company
    - open the boe export wizard vie the "BOE" button
    - complete the wizard and click Generate BOE

This fix adds "l10n_es.mod390.tax.report.handler" as custom handlers to the sections enabling to call 'export_boe'

Task: 4453629
X-original-commit: d1c1bf7791713dc5277e918012c347d516483058
Part-of: odoo/enterprise#78342
Related: odoo/odoo#196101
Signed-off-by: Josse Colpaert (jco) <jco@odoo.com>
Signed-off-by: de Wouters de Bouchout Jean-Benoît (jbw) <jbw@odoo.com>