[FIX] l10n_mx_edi_pos: prevent TypeError while generate invoice for refund order
When a user tries to validate an invoice of the refunded order a traceback will
occur.

Steps to produce:

- Install 'l10n_mx_edi_pos' module.
- Switch to a company whose country code is 'MX'(Mexico).
- Open 'Point of Sale' and New Session.
- Select any products > payment > Select payment method > Invoice >
Select customer > Validate.
- Click on 'Next Order'.
- Click on 'Refund and select your order.
- Click on refund > payment > Select payment method >
Invoice > Validate.
- Error will be generated.

Error: TypeError: can only concatenate str (not bool) to str

This is because 'l10n_mx_edi_cfdi_uuid' is empty at [1], And a string
concatenate with it.

link [1]: https://github.com/odoo/enterprise/blob/1502f8b3e519d41f4a58e2acc846f315f6f5eeda/l10n_mx_edi_pos/models/pos_order.py#L150

This commit solves the above issue while checking the existence of
 'l10n_mx_edi_cfdi_uuid'  while creating  the  invoice for refund_order

sentry-4935781389

closes odoo/enterprise#66347

X-original-commit: c283ae98798f7387896ce03b4471d3fe387e35be
Signed-off-by: Julien Van Roy (juvr) <juvr@odoo.com>
Signed-off-by: Meet Gandhi (mega) <mega@odoo.com>