[FIX] l10n_ke_edi_oscu: give valid attribute name
Currently, an error occurs when the system tries to access the attribute name
'account_fiscal_id' through 'company_id' [1] but it is not available in
res_company model.

Step to produce:

- Install the 'l10n_ke_edi_oscu_stock' module.
- Create a product, Set a company as Kenya, Change a 'Product Type'
storable to service or consumable.
- Again change a 'Product Type' to a storable product.

AttributeError: 'res.company' object has no attribute 'account_fiscal_id'

Link [1]: https://github.com/odoo/enterprise/blob/3f0113b0d95200466f51b9c1f75b58a3534fb34c/l10n_ke_edi_oscu_stock/models/product.py#L21-L22

To resolve this issue, Get a product country code from 'account_fiscal_country_id' instead of 'account_fiscal_id'

Sentry-5862212825

closes odoo/enterprise#70148

Signed-off-by: Antoine Dupuis (andu) <andu@odoo.com>