[FIX] l10n_mx_edi: prevent an error when upload an XML with tax
Currently, an error occurs when uploading an XML file to generate an invoice.

Step to produce:

- Install the 'l10n_mx_edi' module.
- Go to Accounting / Configuration / Accounting / Taxes, And delete all 'Exento'
taxes.
- Go to Accounting / Configuration / Accounting / Tax Groups, And delete all
'Exento' Tax Group.
- Navigate to Accounting / Customers / Invoices, And upload an XML file to
generate an invoice,
- Ensure that the XML file contains the "TipoFactor" with a value of "Exento".
(use this XML file [1]).

AttributeError: 'NoneType' object has no attribute 'id'

An error occurs when attempting to generate an invoice by uploading an XML file
because system tries to retrieve an ID from the external_id of a tax group at
[2] which is not available.

link [1]: https://github.com/odoo/enterprise/blob/1e3dfa7c6a57c251d77801c316818b5a9fae6cc5/l10n_mx_edi/tests/test_files/test_bill_import_extento.xml#L1

link [2]: https://github.com/odoo/enterprise/blob/1e3dfa7c6a57c251d77801c316818b5a9fae6cc5/l10n_mx_edi/models/account_move.py#L2381

To resolve the issue, Add a condition to ensure that an external_id of a tax
group is available.

sentry-5312222893

closes odoo/enterprise#63874

X-original-commit: e51441aae2e47fd20e9f60857694b2ea92e57a4f
Signed-off-by: Florian Gilbert (flg) <flg@odoo.com>