[IMP] hr_appraisal, hr_appraisal_survey: record should be passed in template context if mail_notification_light is customized
Steps to reproduce :
----
- customize mail_notification_light template with a field from record
  (with Studio or with inherited template)
- confirm a Hr Appraisal or send a Hr Appraisal Survey

Error before this commit :
----
- RPC error
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
KeyError: 'record'
Template: mail.mail_notification_light

Explanation :
----
We add the record in the template context, therefore any field from the
record can be called

closes odoo/enterprise#79368

X-original-commit: c9b0bca0c76b90ee35cc4d64df0d60c7f8e54633
Signed-off-by: Cyril VINH-TUNG (INVITU) <cyril@invitu.com>
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>