[FIX] hr_contract_salary/17.0: Internal Server Error
  Steps to Reproduce:
 -------------------
 1. Install hr_contract_salary module, create an advantage.
 2. In the advantages 'Display Type' field should be 'Always selected'.
 3. Leave the res_field_id field empty.
 4. Put this advantage as Mandatory Advantage for another field.
 5. Open Recruitement App, create and send an offer.
 6. Go to Offers smart button and open the Offer link.
 7. There will be an Internal Server Error.

 To resolve this issue we'll just continue wherever the res_field_id is not set. Because
 if the res_field_id is not set it'll have no value which in return gives False(bool) which
 can't be appended.

 Traceback:

```py
 Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1770, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/17.0/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1797, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1914, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/enterprise/17.0/hr_contract_salary/controllers/main.py", line 231, in salary_package
    values = self._get_default_template_values(contract, offer)
  File "/home/odoo/src/enterprise/17.0/hr_contract_salary/controllers/main.py", line 131, in _get_default_template_values
    values = self._get_salary_package_values(contract, offer)
  File "/home/odoo/src/enterprise/17.0/hr_contract_salary/controllers/main.py", line 411, in _get_salary_package_values
    mapped_benefits, mapped_dependent_benefits, mandatory_benefits, mandatory_benefits_names, benefit_types, dropdown_options_2, dropdown_group_options, initial_values_2 = self._get_benefits_values(contract, offer)
  File "/home/odoo/src/enterprise/17.0/hr_contract_salary/controllers/main.py", line 397, in _get_benefits_values
    dependent_name = dependent_benefit.field + '_' + dependent_benefit.display_type
TypeError: unsupported operand type(s) for +: 'bool' and 'str'
```

closes odoo/enterprise#62255

Signed-off-by: Sofie Gvaladze (sgv) <sgv@odoo.com>