[FIX] l10n_mx_hr_payroll: cannot generate payslip
Using a newly created payslip structure for Mexico it is not possible to
generate payslips

Steps to reproduce:
- With an MX Company setup
- Go to Payroll > Configuration > Salary > Structures
- Create new structure with the following attributes:
  - Type: "Mexico: employee"
  - Country: "Mexico"
- Go to Payroll > Payslips > Batches, create a new batch
- Click "Generate Payslips"
- Select the freshly created salary structure in the wizard, then click "Generate"

Issue: An error is raised while creating the payslip
Error: float() argument must be a string or a real number, not 'NoneType'

This occurs because we don't have a fallback in `_get_paid_amount`

opw-4328900

closes odoo/enterprise#77277

Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>