[FIX] delivery_ups_rest: fix traceback on delivery validation
Steps to reproduce:
Make a delivery operation from the United States to Canada or
Puerto Rico. Attept to validate the delivery. A traceback appears:

```
File "/home/odoo/src/enterprise/delivery_ups_rest/models/delivery_ups.py", line 154, in ups_rest_send_shipping
result = ups._send_shipping(
File "/home/odoo/src/enterprise/delivery_ups_rest/models/ups_request.py", line 406, in _send_shipping
request['Shipment']['InvoiceLineTotal'] = {
KeyError: 'Shipment'
```

To fix the issue we need to access `request['ShipmentRequest']['Shipment']`
instead of `request['Shipment']`.

opw-3710939

closes odoo/enterprise#57172

X-original-commit: 366a5d58ab1152bb3e04f34bd65f1db98c50e0c7
Signed-off-by: Tiffany Chang (tic) <tic@odoo.com>
Signed-off-by: Ahmad Khanalizadeh (khah) <khah@odoo.com>