[FIX] hr_appraisal_survey: prevent the TypeError error when uninstalling module
Currently, an error occurs when the user tries to uninstall the
`hr_appraisal_survey` module.

error: `AttributeError: module 'odoo.addons.hr_appraisal_survey' has no
attribute 'uninstall_hook'`

This is because the recently refactored code with [1] in saas-17.2 removes the
`uninstall_hook` method, but its reference is still present in the manifest.

This commit will fix the above issue by removing `uninstall_hook`
from the manifest.

[1]-https://github.com/odoo/enterprise/commit/8487fc4e7464316539c3ecaebd1844a556ed0c86
sentry-5174558827

closes odoo/enterprise#60658

X-original-commit: 5a65c749787e2674bbe109487fd4878f614ce940
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>
Signed-off-by: ANSARI MAHAMADASIF (maan) <maan@odoo.com>