[FIX] social_instagram: resolve traceback
Whenever there is faulty data, it returns only one value, but it requires two.
I have made a fix for that.

Traceback group: 1415

```py
('social.menu_social_post', 609, 'Social Marketing > Posts', 860):
 Traceback (most recent call last):
   File /tmp/tmpccnj1owi/migrations/base/tests/test_mock_crawl.py, line 256, in crawl_menu
    self.mock_action(action_vals)
   File /tmp/tmpccnj1owi/migrations/base/tests/test_mock_crawl.py, line 429, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File /tmp/tmpccnj1owi/migrations/base/tests/test_mock_crawl.py, line 458, in mock_view_form
    [data] = record.read(fields_list)
   File /home/odoo/src/odoo/saas-17.4/odoo/models.py, line 3670, in read
    return self._read_format(fnames=fields, load=load)
   File /home/odoo/src/odoo/saas-17.4/odoo/models.py, line 3902, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
   File /home/odoo/src/odoo/saas-17.4/odoo/models.py, line 6727, in __getitem__
    return self._fields[key].__get__(self)
   File /home/odoo/src/odoo/saas-17.4/odoo/fields.py, line 1263, in __get__
    self.compute_value(recs)
   File /home/odoo/src/odoo/saas-17.4/odoo/fields.py, line 1445, in compute_value
    records._compute_field_value(self)
   File /home/odoo/src/odoo/saas-17.4/addons/mail/models/mail_thread.py, line 428, in _compute_field_value
    return super()._compute_field_value(field)
   File /home/odoo/src/odoo/saas-17.4/odoo/models.py, line 5037, in _compute_field_value
    fields.determine(field.compute, self)
   File /home/odoo/src/odoo/saas-17.4/odoo/fields.py, line 101, in determine
    return needle(*args)
   File /home/odoo/src/enterprise/saas-17.4/social_instagram/models/social_post_template.py, line 36, in _compute_instagram_preview
    faulty_images, error_code = post._get_instagram_image_error()
 ValueError: too many values to unpack (expected 2)
```

closes odoo/enterprise#68590

X-original-commit: 9e6d74685d6f2475e0848813bb079c3fec67a24c
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>