[FIX] sign: internal server error in sign portal navigation
Before this commit:
When a portal user navigates through the Signatures using the arrow buttons, an error "500: Internal Server Error" is raised.

Traceback error:
values = self._get_page_view_values(sign_item_sudo, sign_item_sudo.access_token, values,
TypeError: CustomerPortal._get_page_view_values() got multiple values for argument 'access_token'

This happened because the argument 'access_token' is passed two times:
1. sign_item_sudo.access_token
2. in **kwargs

This commit aims to fix the issue by deleting 'access_token' from kwargs.

closes odoo/enterprise#61693

Task: 3853020
X-original-commit: 96d2d0fd7c9763d94f38ab05822b4d82e03a0312
Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>