[FIX] sale_subscription: fixed typeError for next_invoice_date
`next_invoice_date` field is not required field and was using
on computation of `display_late`  field and used
`order.next_invoice_date < today` without checking
if order.next_invoice_date. so for some record
we found NULL value for next_invoice_date and will get
traceback from that line during upgrade

```
File "/home/odoo/src/enterprise/17.0/sale_subscription/models/sale_order.py", line 502, in _compute_display_late
    order.display_late = order.subscription_state in SUBSCRIPTION_PROGRESS_STATE and order.next_invoice_date < today
 TypeError: '<' not supported between instances of 'bool' and 'datetime.date'

```

closes odoo/enterprise#52148

Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>