[IMP] l10n_uy_edi: Entrega Gratuita 100% Disc line
Some users need to make invoices with 100% discount lines. If they try
then will receive this UCFE error that does not let us to validate the
invoice in DGI::

  ERROR: CODE 31: Error: El contenido del elemento 'Item' en espacio de
  nombres 'http://cfe.dgi.gub.uy' está incompleto. Lista esperada de
  elementos posibles: 'SubDescuento, RecargoPct, RecargoMnt, SubRecargo,
  RetencPercep, MontoItem' en espacio de nombres 'http://cfe.dgi.gub.uy'.

In order to make it work we need to adapt the module to accept this kind
of lines that actually represent an "Entrega Gratuita" (Indicator 5 in
Uruguay)

* We check if the line is a 100% discount, if it is then we marked as
  Entrega Gratuita when we are creating XML (Indicator 5)
* Now that we can have lines and also invoices with total value 0.0 we
  need to adapt our XML because if value 0.0 then some tags were not
  added to the final XML - it was interpreted as False and the result
  was and invalid XML becasue we were missing a mandatory tag.
* Now that we can tags that have 0.0 value to the final XML we have a
  problem with the compute of the foreign currency (division by zero),
  to avoid it we detect this cases and use the date rate. Also, the rate
  is only been computed when actually we are going to use it.

LATAM 1296 / ADHOC Ticket 83295

closes odoo/enterprise#73956

Signed-off-by: Antoine Dupuis (andu) <andu@odoo.com>