[FIX] account_invoice_extract: searching state with country id
Currently an exception was generated when [1] found as multiple state.

error: `ValueError: Expected singleton: res.country.state(1674, 18)`

This is because [1] searches the state based on state name, but in many scenario
the state name maybe repeated for different country eg. United States of America
an Uruguay both has same state 'Florida'

This commit will fix the above issue by adding country id in searching state so
we always get state based on country.

[1] - https://github.com/odoo/enterprise/blob/f3957dc33d956f55b77520167fc9b8ce9dad8c43/account_invoice_extract/models/account_invoice.py#L574

Sentry-6130462157

closes odoo/enterprise#77853

X-original-commit: 2b93b61d41925059e59504d47ebb96a552cfec00
Signed-off-by: Louis Baudoux (lba) <lba@odoo.com>
Signed-off-by: Kishan Kumar Jaiswal (kkuj) <kkuj@odoo.com>