[FIX] l10n_br_sale_subscription: correctly override a t-call
Currently, you view subscription quotations in the portal with a
Brazilian company.

Steps to reproduce
------------------
* install `l10n_br_sales`
* switch to a Brazilian company
* attempt to "Preview" the subscription quotation

You should be met with the following traceback:
```
AttributeError: 'NoneType' object has no attribute 'decimal_places'
Template: l10n_br_sales.document_tax_totals_brazil
Path: /t/tr[2]/td[2]/strong
Node: <strong t-out="tax_totals[\'total_amount_currency\']" t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: currency}"/>
```

opw-4247492

closes odoo/enterprise#72092

Signed-off-by: Florian Gilbert (flg) <flg@odoo.com>