[FIX] sale_purchase_inter_company_rules: fix picking validation
Steps to reproduce:
* enable inter-company transactions
* enable "Synchronize Sales and Purchase Order" in company B
* enable "Copy Lots on Delivery Validation" in company B
* create an SO from company A to company B with a single product, confirm
* go to Delivery, click Validate

Odoo will show an error popup:
"AttributeError: 'stock.move' object has no attribute 'quantity_done'"

The issue is caused by a recent refactoring in odoo/odoo#137864

closes odoo/enterprise#49645

Signed-off-by: Arnold Moyaux (arm) <arm@odoo.com>