[FIX] l10n_it_reports: Bill prediction, fix dependencies
There are cases in which people uninstall `l10n_it_edi`
so the following traceback is given when importing a PDF invoice (OCR):

```
File "/home/odoo/src/enterprise/saas-16.4/l10n_it_reports/models/account_move.py", line 9, in <lambda>
    lambda rec: self.env['account.edi.format']._check_filename_is_fattura_pa(rec.name)
AttributeError: 'account.edi.format' object has no attribute '_check_filename_is_fattura_pa'
```

We move everything back to `l10n_it_edi`, but the test will be excised.

Community PR: ???
opw-???

closes odoo/enterprise#53750

X-original-commit: 8bd8464b759d4db43c79b3c5dfddfba1029db7eb
Related: odoo/odoo#148379
Signed-off-by: Josse Colpaert <jco@odoo.com>
Signed-off-by: Paolo Gatti (pgi) <pgi@odoo.com>