[FIX] project_enterprise: prevent attributeerror on removing planned date
When task assignees have more than one task at the same time in field service, 
and tries to remove the planned date from one of the tasks,
A traceback will appear.

Steps to reproduce the error:
- Go to Field Service > Create a new task with the planned date and Assignees
- Create another task with the same planned date and Assignees > Save
- Now try to remove the planned date

Error: A traceback appears:
"AttributeError: 'bool' object has no attribute 'tzinfo'"

https://github.com/odoo/enterprise/blob/74e8fa829cf17677ddcb29d91a0521d5d5b9a1b6/project_enterprise/models/project_task.py#L229-L230
When the user removes the planned date,
"planned_date_begin" and "date_deadline" will be False.
So it will lead to the above traceback.

sentry-5444639133

closes odoo/enterprise#64708

X-original-commit: 8044f4c82c975222cb45f8ddea7496c6621d6eee
Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>
Signed-off-by: Renilkumar Kajavadra (reka) <reka@odoo.com>