[FIX] l10n_in_reports_gstr: traceback while generating spreadsheet
Steps to reproduce traceback:
1. Create an overseas invoice with `IGST 0`
2. Post the Invoice
3. Create GSTR Report for the following month
4. Click on Generate Button
traceback:
```py
Traceback (most recent call last):
  File "/home/odoo/odoo/enterprise/l10n_in_reports_gstr/tests/test_gstr1_report.py", line 233, in test_gstr1_export_with_igst_zero
    gstr1_json = gstr1_report._get_gstr1_json()
  File "/home/odoo/odoo/enterprise/l10n_in_reports_gstr/models/gst_return_period.py", line 1114, in _get_gstr1_json
    'exp': _get_exp_json(AccountMoveLine.search(self._get_section_domain('exp'))),
  File "/home/odoo/odoo/enterprise/l10n_in_reports_gstr/models/gst_return_period.py", line 932, in _get_exp_json
    for line_tax_details in tax_details.values():
AttributeError: 'NoneType' object has no attribute 'values'
```

After this commit-
We fix the above traceback and on further investigation
it was found that `hsn`, `b2b` and `cdnr` were
missing `zero_rated` base tag in their domain
which we fix in this commit

task-4195917

closes odoo/enterprise#70422

X-original-commit: 5937e64c6f578e5dd20c251224cc08da6a1f795c
Signed-off-by: Antoine Dupuis (andu) <andu@odoo.com>
Signed-off-by: Harsh Modi (hamo) <hamo@odoo.com>