[FIX] mrp_workorder: pass noupdate = 1 for demo record
when database uploaded without demo data and there is
no any record in mrp production, and customer used
load sample demo data, then it will create some demo
record from this file which was actually defined in
mrp/data/mrp_demo.xml with noupdate= True.

but as this xmlids has been created from python file
using load samples it's noupdate='f' .
so without demo flag, we have `mrp.mrp_inventory_1`
and `mrp.mrp_inventory_2` quant entry with noupdate='f'

so during upgrade as there was no demo file loaded,
and this entry are with noupdate='f'
ORM try to remove those record quants record
in `_process_end` during upgrade from 17.0 to
saas-17.1, and which was create issues as
that quant contain some qty for storable product
so after upgrade as this qunts removed we have mismatched
qty compare to before upgrade ( original database)
so to fix that we need to pass noupdate='t'
and also need to fix in upgrade script with force_noupdate
TRue.

```
Traceback (most recent call last):
  File "/tmp/tmpf_o_71pk/migrations/testing.py", line 207, in test_check
    self.check(value)
  File "/tmp/tmpf_o_71pk/migrations/stock/tests/test_on_hand_quantity.py", line 58, in check
    self.assertEqual(before_results, self.convert_check(after_results), self.message)
AssertionError: Lists differ: [[3, '1'], [4, '4'], [6, '2'], [7, '5'], [8[541 chars]36']] != [[6, '2'], [7, '5'], [8, '2'], [9, '1'], [1[521 chars]36']]

First differing element 0:
[3, '1']
[6, '2']
```

X-original-commit: ce53bae6b74ce44590221625e7a5e6047996b542
Part-of: odoo/enterprise#58515