[FIX] sale_amazon: better error message if location missing info
Before this commit:
An exception was raised if the location was failing to retrieve
necessary information. Example:
```
ElementTree.SubElement(ship_from_, 'AddressFieldOne').text = location_.street[:180]
TypeError: 'bool' object is not subscriptable
```

After this commit:
A more user-friendly error message is shown indicating more clearly
the problematic record and missing information

opw-3936775

closes odoo/enterprise#68252

X-original-commit: 6503f1ea9ed3742bf5b8415685fdc6744d33314b
Signed-off-by: Loan Sens (lse) <lse@odoo.com>