[FIX] hr_recruitment_integration_monster: error when publishing job on monster
When the user tries to publish a job position on the job board monster,
a traceback will appear.

Steps to reproduce the error:
- Install "hr_recruitment_integration_monster" module
- Go to Recruitment > Applications > By Job Positions >
  Click on the dropdown menu of any job position > Configuration
  (Make sure that the job position is published on the website)
- Add Salary Range > Publish on Job Board > Job Board: Monster.com > Post

Error: A traceback appears:
"AttributeError: 'int' object has no attribute 'monster_id'"

https://github.com/odoo/enterprise/blob/245a38f320db56fd22d946471f626adf6cfeb397/hr_recruitment_integration_monster/wizard/hr_recruitment_post.py#L130-L146
Here, "monster_time_unit" is integer, it does not have "monster_id" attribute.

sentry-6027416420

closes odoo/enterprise#73055

Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>