[FIX] account_budget: fixed syntax error
During upgrade this issue raises.
when there is no value for account_ids and fnames
pod_condition because null and

all_conditions condition also become null
so need to set `sql(FALSE)` if there is no fnames

this is the query where problem occure
during parsing

```
  WITH purchase_order_data AS (SELECT (pol.product_qty - pol.qty_invoiced) / po.currency_rate * pol.price_unit::FLOAT * (a.rate)::FLOAT AS committed,
                               0 AS achieved,
                               "a"."account_id", "a"."x_plan3_id", "a"."x_plan4_id", "a"."x_plan5_id"
                          FROM purchase_order_line pol
                          JOIN purchase_order po ON pol.order_id = po.id
                    CROSS JOIN JSONB_TO_RECORDSET(pol.analytic_json) AS a(rate FLOAT, "account_id" INT, "x_plan3_id" INT, "x_plan4_id" INT, "x_plan5_id" INT)
                         WHERE po.date_order >= '2024-09-01'::date
                           AND po.date_order <= '2024-09-30'::date
                           AND pol.qty_invoiced < pol.product_qty
                           AND po.company_id = 1
                           AND po.state in ('purchase', 'done')
                           AND
                    ),

    account_analytic_line_data AS (
                        SELECT 0 AS committed,
                               aal.amount AS achieved,
                               "aal"."account_id", "aal"."x_plan3_id", "aal"."x_plan4_id", "aal"."x_plan5_id"
                          FROM account_analytic_line aal
                         WHERE aal.date >= '2024-01-01'::date
                           AND aal.date <= '2024-01-31'::date
                           AND aal.company_id = 1
                           AND
                           AND aal.category in ('vendor_bill')

```

```
 File "/home/odoo/src/enterprise/saas-17.4/account_budget/models/budget_line.py", line 136, in _compute_all
    self.env.cr.execute(SQL(
   File "/home/odoo/src/odoo/saas-17.4/odoo/sql_db.py", line 564, in execute
    return self._cursor.execute(*args, **kwargs)
   File "/home/odoo/src/odoo/saas-17.4/odoo/sql_db.py", line 347, in execute
    res = self._obj.execute(query, params)
 psycopg2.errors.SyntaxError: syntax error at or near ")"
LINE 14:                     ),

```

closes odoo/enterprise#70326

X-original-commit: 293aeecdd51a2596f30ac2385f7fbfdfd97b3227
Signed-off-by: Olivier Colson (oco) <oco@odoo.com>