[FIX] data_merge: fix install-time rule checks
Since odoo/odoo@f0cb56f3651da487c1f4fe34adc25e7401678703 we check rules
domains. This has the side effect of making rules in data_merge fail
because they may pertain models that are yet to be loaded by the ORM.

Steps to reproduce:
1. Install `crm` and `data_merge` on a new DB
2. Run data merge for `crm.leads`
   Data Cleaning > Configuration > Deduplication Rules >
   Lead/Opportunity > DEDUPLICATE
3. Try to install data_merge module `./odoo-bin ... -i data_merge`

We get a `ParseError`:
```
...
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 694, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /home/odoo/src/enterprise/15.0/data_merge/security/security.xml:4
Invalid domain: 'crm.lead'
```

This issue happens during upgrades 14.0->15.0

The actual reason for the failure is that this line
https://github.com/odoo/odoo/blob/dbd37953957b94a2e05908d96cf8e4d7dea42d72/odoo/addons/base/models/ir_rule.py#L79
eventually gets into
https://github.com/odoo/enterprise/blob/0db3d7c9473034da0714f96fe915a7dedb7b667e/data_merge/models/data_merge_record.py#L101
and this causes a `KeyError` because `crm.lead` is not loaded yet.

This error didn't happen before because at XML load there was no attempt
to generate a `Query` from a domain expression. After the linked commit
above we now force the parse of such queries. That involves the call to
`_search_company_id` for `data_merge.record` entries.

The patch proposed here skips `ValidationError`s at install of
`data_merge`. This still keeps the validation active for usual DB
operations.

closes odoo/enterprise#55884

X-original-commit: 3aa6dc9efbcae87774da888a5fb94178be87849a
Signed-off-by: Sofie Gvaladze (sgv) <sgv@odoo.com>
Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>