[FIX] sign: traceback when cancelling the flow of a template
Before this commit, when we canceled a sign request, a traceback would
occurs:

```
UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of undefined (reading 'doAction')
TypeError: Cannot read properties of undefined (reading 'doAction')
```

Even if goBackToKanban is correctly binded, controlPanelProps was not
calling it properly.

Moreover, since https://github.com/odoo/odoo/pull/145362/files#diff-9cd8e9097d772fd31d523de85a6a9824043e4e1d3ec0d424eab598969751558eR1-R46
session.uid can't be used anymore to get the current user id.
user.userId has the necessary information

closes odoo/enterprise#64321

Taskid: 3932003
X-original-commit: 7cc701ab910198602d23947610b94ecdf44463cf
Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>