[FIX] account_accountant: traceback when missing residual in currency
Users manually reconciling foreign currency entries sometimes do not
perfectly balance the operation. In this case the system needs to
collect the amount residual by currency and propose a write-off.
Currently the system will raise a traceback when the residual amount is
only in foreign currency

Steps to reproduce:
- Have a foreign currency (EUR) with exchange rate 36.0
- Have a Journal [JNL] in foreign currency
- In [JNL] register a Vendor Payment of amount 51,993.01 EUR (1444.25 USD)
- In [JNL] register a new transaction as follows:
  - Foreign currency: USD
  - Amount in Currency: 1444.25
- Open Journal Items and select:
  - The credit entry from the Vendor Payment
  - The debit entry from the transaction
- Reconcile

Issue: A traceback will raise
```
  File "[...]/account_accountant/wizard/account_reconcile_wizard.py", line 337, in <genexpr>
    residual_values[amls.company_currency_id]['residual']
KeyError: res.currency(1,)
```

opw-4514336

closes odoo/enterprise#78735

Signed-off-by: Antoine Dupuis (andu) <andu@odoo.com>