[FIX] l10n_cl_edi: prevent an error when running fetch mail﻿
Currently, an error is generated when run 'Mail: Fetchmail Service' scheduled
action.

Step to produce:

- Install the 'l10n_cl_edi' module.
- And manually trigger the 'Mail: Fetchmail Service' scheduled action.

TypeError: FetchmailServer.fetch_mail() got an unexpected keyword argument
'raise_exception'

The issue arises during the execution of the 'Mail: Fetchmail Service'
scheduled action because the 'fetch_mail()' method call without argument, as we
can see at [1], And this argument is added from this PR.

link [1]: https://github.com/odoo/enterprise/blob/ba99dd4c236353c43376210a9aabcb0af5bd0299/l10n_cl_edi/models/fetchmail_server.py#L51

To resolve the issue, Add a default keyword argument at [2] to prevent an issue.

link [2]: https://github.com/odoo/enterprise/blob/ba99dd4c236353c43376210a9aabcb0af5bd0299/l10n_cl_edi/models/fetchmail_server.py#L51

sentry-5284073241

closes odoo/enterprise#64393

X-original-commit: 84ccd25e54b4e3c4d0bf00b2a2207db84f488560
Signed-off-by: William André (wan) <wan@odoo.com>