[FIX] account_reports: aged receivable filter days interval
Steps to reproduce:
 - Open Aged Receivable report
 - Press the Days Interval filter
 -> Traceback stating "TypeError: optionPath.split is not a function"

The issue was introduced in the following commit, which reworked how filters are updated: https://github.com/odoo/enterprise/commit/10d61ca19ea850be7023043051c31f2b4bd3354c

task-4122464

closes odoo/enterprise#68569

X-original-commit: 0536682b63ff7df8a5be943dc378d3f434d4b1d7
Signed-off-by: Wala Gauthier (gawa) <gawa@odoo.com>