[FIX] web_studio: prevent crash with an empty groups attribute
Steps to reproduce
==================

- Install account_accountant,l10n_fr_invoice_addr,web_studio,website_sale
- Go to invoices
- Open studio

```
enterprise/web_studio/models/ir_ui_view.py:103 in _postprocess_access_rights
   100 │   │   │   for node in tree.xpath('//*[@groups]'):
   101 │   │   │   │   node_groups[node] = node.get('groups')
❱  103 │   │   │   │   if not self.user_has_groups(node.get('groups')):

odoo/odoo/models.py:1550 in user_has_groups
❱ 1550 │   │   │   if group_ext_id[0] == '!':
  1551 │   │   │   │   not_has_groups.append(group_ext_id[1:])

IndexError: string index out of range
```

Cause of the issue
==================

The l10n_fr_invoice_addr sets an [empty group] attribute on a node.
When opening studio, user_has_groups is called with the groups attribute
value. In this case, it's an empty string and it fails.

Solution
========

Since an empty group is [allowed] by the ORM, we simply check that the
value is not empty before calling user_has_groups

---

[empty group]: https://github.com/odoo/odoo/blob/00a78373f87c84dfa8ffa97ca255cf01368cd423/addons/l10n_fr_invoice_addr/models/account_move.py#L17
[allowed]: https://github.com/odoo/odoo/blob/a913272136182e6f4b1e28337686dd14616ea0ca/odoo/addons/base/tests/test_views.py#L2791

opw-4046078

closes odoo/enterprise#66682

X-original-commit: 153fad570461d39b60f84c8fa7a7b5d65806a00c
Signed-off-by: Lucas Perais (lpe) <lpe@odoo.com>
Signed-off-by: Hubert Van De Walle <huvw@odoo.com>