[FIX] l10n_uy_edi: traceback (not valid UY id)
When trying to invoice to a partner that does not have an
uruguayan identification type or do not have a genric identification
type a traceback appears:

  File "/data/build/enterprise/l10n_uy_edi/models/account_move.py", line 502, in _l10n_uy_edi_check_move
    dtype=self.partner_id.l10n_latam_document_type_id.name))
AttributeError: 'res.partner' object has no attribute 'l10n_latam_document_type_id'

This happens because the document type is related to the invoice, the
partner actually has identification type field.

closes odoo/enterprise#72060

X-original-commit: 37577535a4482eaa1250b41136b47b3613eb7693
Signed-off-by: Josse Colpaert (jco) <jco@odoo.com>