[FIX] account_accountant: Add missing xmlid on init hook
The post-init hook of this module runs `ChartTemplate._load_data`
and that might reference the xmlid of a general journal from the
company. If that xmlid is missing, it will fail with the error:
```
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7f9ff24b1240>, 'account.1_general')
```

Steps to reproduce on a fresh 17.0 database:
- Install a localization module, eg `l10n_be`.
- This will create the necessary xmlids. Delete the 'X_general'
xmlids from the dabase.
- Install `account_accountant`. Installation will fail with the
aforementioned error.

This also happens during upgrades. Modules like `l10n_uk` install
`account_accountant` during the upgrade.
Since the 'X_general' xmlids are not created in version 16.0,
the upgrade will automatically fail when the module is installed.

closes odoo/enterprise#59512

Signed-off-by: Habib Ayob (ayh) <ayh@odoo.com>