[FIX] account_asset: fix singletonerror when creating asset
When the customer tries to create an asset for multiple journal items from
different companies, a traceback will appear.

Steps to reproduce the error:
- Create an invoice with Company A
- Create an invoice with Company B
- Go to Accounting > Journal Items > select both invoice > Create Asset

Error: A traceback appears:
'ValueError: Expected singleton: res.company(1, 5)'

https://github.com/odoo/enterprise/blob/9373f9bac47839e3314a7823e05d4ef61af0b3e3/account_asset/models/account_move.py#L345
Here, When the user creates an asset for multiple journal items from
different companies, Self has multiple 'company_id'.
So it will lead to the above traceback.

sentry-5613448397

closes odoo/enterprise#67467

X-original-commit: 0b55bd768f2bdc0d7b3d445b5e20cb9845793bd7
Signed-off-by: Wala Gauthier (gawa) <gawa@odoo.com>
Signed-off-by: Renilkumar Kajavadra (reka) <reka@odoo.com>