[FIX] spreadsheet_edition: Fix JSONDecodeError during compute
if their is nothing to read in attachment file realted SO,
it will bring empty byte(b'') that is here and when it go
for decode it will raise this traceback
```
Traceback (most recent call last):
   File "/tmp/tmp3fwx3zdj/migrations/base/tests/test_mock_crawl.py", line 256, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmp3fwx3zdj/migrations/base/tests/test_mock_crawl.py", line 429, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmp3fwx3zdj/migrations/base/tests/test_mock_crawl.py", line 532, in mock_view_kanban
    self.mock_web_search_read(model, view, [domain], fields_list)
   File "/tmp/tmp3fwx3zdj/migrations/base/tests/test_mock_crawl.py", line 591, in mock_web_search_read
    data = model.search_read(domain=domain, fields=fields_list, limit=80)
   File "/home/odoo/src/odoo/saas-17.4/odoo/models.py", line 5847, in search_read
    return records._read_format(fnames=fields, **read_kwargs)
   File "/home/odoo/src/odoo/saas-17.4/odoo/models.py", line 3902, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
   File "/home/odoo/src/odoo/saas-17.4/odoo/models.py", line 6727, in __getitem__
    return self._fields[key].__get__(self)
   File "/home/odoo/src/odoo/saas-17.4/odoo/fields.py", line 1263, in __get__
    self.compute_value(recs)
   File "/home/odoo/src/odoo/saas-17.4/odoo/fields.py", line 1445, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/saas-17.4/addons/mail/models/mail_thread.py", line 428, in _compute_field_value
    return super()._compute_field_value(field)
   File "/home/odoo/src/odoo/saas-17.4/odoo/models.py", line 5037, in _compute_field_value
    fields.determine(field.compute, self)
   File "/home/odoo/src/odoo/saas-17.4/odoo/fields.py", line 101, in determine
    return needle(*args)
   File "/home/odoo/src/enterprise/saas-17.4/spreadsheet_edition/models/spreadsheet_mixin.py", line 44, in _compute_current_revision_uuid
    snapshot = spreadsheet._get_spreadsheet_snapshot()
   File "/home/odoo/src/enterprise/saas-17.4/spreadsheet_edition/models/spreadsheet_mixin.py", line 233, in _get_spreadsheet_snapshot
    return json.loads(base64.decodebytes(snapshot))
   File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
   File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

for preventing this added a condition of empty payload so it won't
raise traceback

This taceback is raising during upgrade why field
data is empty byte ``b''`` due to that above tracbeack is raised
why as this field introduced
in kanban view on computing it blocking the upgrade
process during read call

closes odoo/enterprise#68392

X-original-commit: fa660204bb31af949921d18b86429c77e1f797a8
Signed-off-by: Rémi Rahir (rar) <rar@odoo.com>