[FIX] data_merge: remove messages linked to unlinked records
Steps to reproduce:
-------------------

- Install `data_merge` and `CRM` module
- Go to CRM and create 2 opportunities with same name
- Activate debug mode and go to `Scheduled Actions`
- Run `Data Merge: Find Duplicate Records` action
- Delete the Deduplication Rule for `Lead/Opportunity`
  (or uninstall `CRM` module)
- Go to Discuss and click on `History` channel

Issue:
------

Error: `Record does not exist or has been deleted.`.

Cause:
------

When uninstalling a module that have a model that is used as `res_model_id`
in a `Deduplication Model`, we do not remove message the message linked
to the record deleted.
Therefore, when opening history channel, we try to access messages
linked to records that might have been deleted.

Solution:
---------

When removing `Deduplication Model`, remove also the messages linked to
the record.

Also, `data_merge_duplicate` template and `action_data_merge_record`
action has been moved from `data_merge` to `data_cleaning` module,
so rename call ref.

opw-3906945

closes odoo/enterprise#67472

X-original-commit: d5dd5e7f9258e7198e625a130550d10cdbf96431
Signed-off-by: Yannick Tivisse (yti) <yti@odoo.com>
Signed-off-by: Nasreddin Boulif (bon) <bon@odoo.com>