[FIX] l10n_es_reports: fix generate BOE in mod349 tax report
Before this commit:
Steps
	1) Install l10n_es_reports
	2) Switch to ES company
	3) Create a EU vendor (any except SPAIN) + add TIN
	4) Create a bill with last month date
	5) Reverse that bill with current month date
	6) Go to Tax reports
	7) Switch to Tax Report (Mod 349) (ES)
	8) Choose date range: This Month
    9) Generate BOE
=> It shows an error with a traceback `/l10n_es_reports/models/aeat_tax_reports.py", line 1257, in _write_type2_refund_records
    previous_report_amount = invoice_line_data['columns'][0]['no_format']
    TypeError: 'NoneType' object is not subscriptable`

After this commit:
BOE in mod349 is generated properly without errors

opw-4055702

closes odoo/enterprise#68276

X-original-commit: a1e3798d9022443328f3901fb5c94094a29f5ff0
Signed-off-by: Wala Gauthier (gawa) <gawa@odoo.com>
Signed-off-by: Ahmed Abdelaziz Hasaneen (aaha) <aaha@odoo.com>