[FIX] l10n_mx_edi_stock{_extended}: error on clicking generate delivery guide
When user click on generate delivery guide in receipts,
a traceback will appear.

Steps to reproduce the error:
- Install "l10n_mx_edi_stock"
- Switch to the Mexican company
- Go to Inventory > Operations > Receipts > Create new record
- In receive from, Select partner from Mexico >
  Add a product (make sure that product has UNSPSC Category) > Validate
- Go to Additional Info > Select Transport Type > Save
- Click on Generate Delivery Guide

Error: A traceback appears:
"AttributeError:'res.partner' object has no attribute 'l10n_mx_edi_colony_code'"

https://github.com/odoo/enterprise/blob/6a0bcd778d3c1481642db040d1334920075d3cf2/l10n_mx_edi_stock/models/stock_picking.py#L347
Since https://github.com/odoo/enterprise/commit/f972faf9cb98c27fe44883789588ab8e957435f8
"l10n_mx_edi_colony_code" field is used, this field is in
the "l10n_mx_edi_extended" module,
so when this module is not installed,
it will lead to the above traceback.

This commit solves this issue by adding "l10n_mx_edi_colony_code" field in
"_l10n_mx_edi_add_domicilio_cfdi_values" method of "l10n_mx_edi_stock_extended" module
to extend "l10n_mx_edi_stock" module.

sentry-5261838949

closes odoo/enterprise#61933

X-original-commit: 1ada436dac8a5b7e3130e699741d3f2c1026d70e
Signed-off-by: Josse Colpaert <jco@odoo.com>
Signed-off-by: Renilkumar Kajavadra (reka) <reka@odoo.com>