[FIX] delivery_fedex: include customs info for `REGIONAL_ECONOMY`
Steps to reproduce:
1. set up FedEx shipping method, choose `REGIONAL_ECONOMY` service type
2. make a sale order from EU to UK, add FedEx shipping
3. confirm the sale order, validate the delivery

Error: `2033: Customs Value is required.`

FedEx requires customs info for `REGIONAL_ECONOMY` service type, so
it should be included accordingly.

opw-3527006

closes odoo/enterprise#52160

X-original-commit: 7824000bf8d9b2c2647f706d0c43e818bec2ec44
Signed-off-by: Tiffany Chang (tic) <tic@odoo.com>
Signed-off-by: Ahmad Khanalizadeh (khah) <khah@odoo.com>