[FIX] iot: prevent an error when select printer
We removed the 'select_iot' method here https://github.com/odoo/enterprise/pull/68325
Since, client's non-updated views still call it, and get a traceback.

AttributeError: The method 'select_iot' does not exist on the model
'select.printers.wizard'

We add it again to fix the issue.

Sentry-5804153543

closes odoo/enterprise#69820

Signed-off-by: Yaroslav Soroko (yaso) <yaso@odoo.com>