[FIX] l10n_account_customer_statement: report values retrieval
Install whatsapp
Create a new template as follows:
- Account: any (real values not needed to reproduce the issue)
- Header Type: Document
- Report: Customer Statement
- Body: Any
Save and Submit for Approval

Issue: Tracback will raise during template generation
"""
TypeError: 'NoneType' object is not subscriptable
Template: l10n_account_customer_statements.customer_statements
"""
This occurs because when generating the report for the template we
miss the correct data.
Partial backport of f0a82fc57826346d7edae1465b35303bc7d1649c

opw-4133970

closes odoo/enterprise#70816

Signed-off-by: Claire Bretton (clbr) <clbr@odoo.com>