[FIX] l10n_es_reports: fix subformulas' of expressions in mod349
In this PR[^1], the expressions `mod_349_statistics_invoices_total_amount_balance`
and `mod_349_statistics_refunds_total_amount_balance` was modified so the engine of
both of them changed from `domain` to `aggregation`. Also the subformula from both
of them were removed. But during the upgrade the engines are being modified but
the subformulas kept same.

Expected condition is having NULL on both of the expressions' subformula.
But because they are not being changed during upgrade so they end up being `sum`
at the end.

When we try to open the `Tax report mod 349` after upgrade, the new engine and old
subformula are conflicting and facing issue here[^2].

Steps to reproduce
1. Install `l10n_es_reports` before the PR above in version `16.0`
2. Upgrade the db to `17.0` by solving the 1st issue of this PR
3. Try to open `Tax report mod 349`

you will see errorlike this:

```
.....
    result = getattr(recs, name)(*args, **kwargs)
  File "/home/odoo/src/enterprise/saas-17.4/account_reports/models/account_report.py", line 4869, in get_report_information
    all_column_groups_expression_totals = self._compute_expression_totals_for_each_column_group(self.line_ids.expression_ids, options, warnings=warnings)
  File "/home/odoo/src/enterprise/saas-17.4/account_reports/models/account_report.py", line 2826, in _compute_expression_totals_for_each_column_group
    current_group_expression_totals = self._compute_expression_totals_for_single_column_group(
  File "/home/odoo/src/enterprise/saas-17.4/account_reports/models/account_report.py", line 3011, in _compute_expression_totals_for_single_column_group
    aggregation_formula_results = self._compute_totals_no_batch_aggregation(column_group_options, aggregation_formulas_dict, column_group_expression_totals, cross_report_expr_totals_by_scope)
  File "/home/odoo/src/enterprise/saas-17.4/account_reports/models/account_report.py", line 3208, in _compute_totals_no_batch_aggregation
    expression_result = self._aggregation_apply_bounds(column_group_options, expression.subformula, formula_result)
  File "/home/odoo/src/enterprise/saas-17.4/account_reports/models/account_report.py", line 3266, in _aggregation_apply_bounds
    group_values = match.groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

[^1]: https://github.com/odoo/enterprise/pull/65074
[^2]: https://github.com/odoo/enterprise/blob/3a7a46ff2404a5c4ca1c0ad676529fc17d9a2234/account_reports/models/account_report.py#L3455-L3461

closes odoo/enterprise#74395

X-original-commit: 96a43875250f519ea2b8a8aa6e9116f9a2e48629
Signed-off-by: Olivier Colson (oco) <oco@odoo.com>
Signed-off-by: Jepbar Asgarov <jeas@odoo.com>