[FIX] helpdesk: prevent error on installing module
Currently a 'ParseError' arises when the user installs the 'helpdesk' module
after deleting 'Your Odoo Periodic Digest' from the 'Digest Emails' in Settings.

Steps to reproduce:
- Install 'digest' module (without demo data)
- Settings > Technical > Email > Digest Emails > Delete 'Your Odoo Periodic Digest'
- Now install 'helpdesk' module

Traceback:
Exception: Cannot update missing record 'digest.digest_digest_default'

ParseError: while parsing /home/odoo/src/enterprise/saas-18.1/helpdesk/data/digest_data.xml:4, somewhere inside
<record id="digest.digest_digest_default" model="digest.digest">
            <field name="kpi_helpdesk_tickets_closed">True</field>
        </record>

The error occurs because the user deleted 'Your Odoo Periodic Digest' and then
installed the 'helpdesk' module. which requires a particular record.

This commit solves the above issue by using forcecreate="False" to bypass
record creation if it violates checks.

https://github.com/odoo/odoo/blob/b794f0f332f473deb2c04eba60baf4761db3b508/odoo/tools/convert.py#L364-L366

sentry-5731062091

closes odoo/enterprise#79676

Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>