[FIX] l10n_mx_edi: missing field definition
With an MX company setup
Create a Payment
Action > Send receipt by email

Traceback will raise
```
KeyError: 'l10n_mx_edi_cfdi_attachment_id'
```
It occurs because the field is not defined on the payment model

opw-4298457

closes odoo/enterprise#73457

Signed-off-by: Josse Colpaert (jco) <jco@odoo.com>